title: On the Learning Mechanisms in Physical Reasoning
description: <a href="https://lishiqianhugh.github.io/" style="color:#FFFFFF;">Shiqian Li*</a>, <a href="https://k101w.github.io/" style="color:#FFFFFF;">Kewen Wu*</a>, <a href="https://wellyzhang.github.io/" style="color:#FFFFFF;">Chi Zhang</a>, <a href="https://yzhu.io/" style="color:#FFFFFF;">Yixin Zhu</a>
theme: jekyll-theme-cayman
