title: LfID_Page
description: <a href="https://lishiqianhugh.github.io/" style="color:#FFFFFF;">Shiqian Li</a>, Kewen Wu, <a href="https://wellyzhang.github.io/" style="color:#FFFFFF;>Chi Zhang</a>, <a href="https://yzhu.io/" style="color:#FFFFFF;>Yixin Zhu</a>
theme: jekyll-theme-cayman
